services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: docker_e_kubernetes
    # expõe 5433 no host para evitar conflito local (no CI pode ignorar)
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./codigo.sql:/docker-entrypoint-initdb.d/00_seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d docker_e_kubernetes"]
      interval: 5s
      timeout: 5s
      retries: 20

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_ADDRESS: db:5432
      POSTGRES_DBNAME: docker_e_kubernetes
    ports:
      - "8200:8200"

volumes:
  pgdata:
