services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: docker_e_kubernetes
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8"
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
    volumes:
      - pgdata_ci:/var/lib/postgresql/data
      - ./codigo.sql:/docker-entrypoint-initdb.d/00_seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d docker_e_kubernetes || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_ADDRESS: db:5432
      POSTGRES_DBNAME: docker_e_kubernetes
    ports:
      - "8200:8200"
    healthcheck:
      # one-liner em Python (sem heredoc nem strings quebradas)
      test: ["CMD-SHELL", "python -c \"import urllib.request,sys; sys.exit(0 if urllib.request.urlopen('http://127.0.0.1:8200/health', timeout=3).getcode()==200 else 1)\""]
      interval: 5s
      timeout: 5s
      retries: 20
    command: ["python","/app/main.py"]
    restart: unless-stopped

volumes:
  pgdata_ci:
