services:
  db:
    image: postgres:16
    container_name: pg-ci
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: docker_e_kubernetes
    ports:
      - "5433:5432"   # local pra prints
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./codigo.sql:/docker-entrypoint-initdb.d/00_seed.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pguser -d docker_e_kubernetes || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 30

  web:
    build:
      context: .
    container_name: web-ci
    depends_on:
      db:
        condition: service_healthy
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_ADDRESS: db:5432
      POSTGRES_DBNAME: docker_e_kubernetes
    ports:
      - "8200:8200"   # local pra prints

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins-ci
    user: root
    environment:
      JAVA_OPTS: -Djenkins.install.runSetupWizard=false
    ports:
      - "8081:8080"   # Jenkins local em 8081 (evita conflito com outro Jenkins)
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
    depends_on:
      - db

volumes:
  pgdata:
  jenkins_home:
